[versions]
agp = "8.7.3"
kotlin = "2.1.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.1"
activityCompose = "1.9.3"
composeBom = "2024.12.01"
hilt = "2.54"
jetbrain = "2.1.0"
googleServices = "4.4.2"
firebase = "33.7.0"
navigationFragment = "1.2.0"
androidxNavigationCompose = "2.8.5"
playServices = "21.3.0"
composeRuntime = "1.7.6"
vertaxAi = "16.0.2"
coroutines = "1.10.1"
markdown = "4.6.2"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-fragment = {group = "androidx.hilt", name = "hilt-navigation-fragment", version.ref = "navigationFragment"}
androidx-navigation = {group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigationCompose"}
hilt-navigation-compose = {group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "navigationFragment"}
firebase-bom = {group = "com.google.firebase", name = "firebase-bom",  version.ref = "firebase"}
firebase-analytics = {group = "com.google.firebase", name = "firebase-analytics"}
firebase-auth-ktx = {group = "com.google.firebase", name = "firebase-auth-ktx"}
firebase-firestore = {group = "com.google.firebase", name = "firebase-firestore"}
google-service = {group = "com.google.gms", name = "google-services", version.ref = "googleServices"}
play-services-auth = {group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServices"}
runtime = {group = "androidx.compose.runtime", name = "runtime", version.ref = "composeRuntime"}
runtime-livedata = {group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "composeRuntime"}
runtime-rxjava2 = {group = "androidx.compose.runtime", name = "runtime-rxjava2", version.ref = "composeRuntime"}
firebase-vertaxai = {group = "com.google.firebase", name = "firebase-vertexai", version.ref = "vertaxAi"}
coroutines-core = {group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines"}
coroutines-android = {group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines"}
markwon-core = {group = "io.noties.markwon", name = "core", version.ref = "markdown"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "jetbrain" }
jetbrain-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "jetbrain" }
google-services = {id = "com.google.gms.google-services", version.ref = "googleServices"}

